### ISSUE TITLE
mantl-storage-setup failure on digitalocean

### ISSUE THREAD

**Issue by siddharthist** [CiscoCloud/mantl#1699]
This causes Docker to fail, eventually. 
```
[root@lb-control-03 ~]# sudo journalctl -u mantl-storage-setup --no-pager
-- Logs begin at Thu 2016-07-14 10:15:03 UTC, end at Thu 2016-07-14 10:35:51 UTC. --
Jul 14 10:28:45 lb-control-03 systemd[1]: Starting mantl-storage-setup.service...
Jul 14 10:28:45 lb-control-03 mantl-storage-setup[19718]: Please enter a physical volume path.
Jul 14 10:28:45 lb-control-03 mantl-storage-setup[19718]: Run `vgcreate --help' for more information.
Jul 14 10:28:45 lb-control-03 mantl-storage-setup[19718]: ==> Processing: /etc/mantl/filesystems.d/10-volume-group.conf
Jul 14 10:28:45 lb-control-03 mantl-storage-setup[19718]: READ:  ['/sbin/pvs', '--nameprefix', '--noheadings', '--unquoted', '-o', 'pv_all,vg_name', '--separator', ';']
Jul 14 10:28:45 lb-control-03 mantl-storage-setup[19718]: READ:  ['/sbin/vgs', '--nameprefix', '--noheadings', '--unquoted', '-o', 'all', '--separator', ';']
Jul 14 10:28:45 lb-control-03 mantl-storage-setup[19718]: Traceback (most recent call last):
Jul 14 10:28:45 lb-control-03 mantl-storage-setup[19718]: File "/usr/bin/mantl-storage-setup", line 296, in <module>
Jul 14 10:28:45 lb-control-03 mantl-storage-setup[19718]: main()
Jul 14 10:28:45 lb-control-03 mantl-storage-setup[19718]: File "/usr/bin/mantl-storage-setup", line 287, in main
Jul 14 10:28:45 lb-control-03 mantl-storage-setup[19718]: iterate_config("group", process_vg, cp)
Jul 14 10:28:45 lb-control-03 mantl-storage-setup[19718]: File "/usr/bin/mantl-storage-setup", line 277, in iterate_config
Jul 14 10:28:45 lb-control-03 mantl-storage-setup[19718]: fun(each, cp)
Jul 14 10:28:45 lb-control-03 mantl-storage-setup[19718]: File "/usr/bin/mantl-storage-setup", line 122, in process_vg
Jul 14 10:28:45 lb-control-03 mantl-storage-setup[19718]: subprocess.check_call([VGCREATE_CMD] + vgoptions + ['-s', str(pesize), name] + list(dev_list))
Jul 14 10:28:45 lb-control-03 mantl-storage-setup[19718]: File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
Jul 14 10:28:45 lb-control-03 mantl-storage-setup[19718]: raise CalledProcessError(retcode, cmd)
Jul 14 10:28:45 lb-control-03 mantl-storage-setup[19718]: subprocess.CalledProcessError: Command '['/sbin/vgcreate', '-s', '4', 'mantl']' returned non-zero exit status 3
Jul 14 10:28:45 lb-control-03 systemd[1]: mantl-storage-setup.service: main process exited, code=exited, status=1/FAILURE
Jul 14 10:28:45 lb-control-03 systemd[1]: Failed to start mantl-storage-setup.service.
Jul 14 10:28:45 lb-control-03 systemd[1]: Unit mantl-storage-setup.service entered failed state.
Jul 14 10:28:45 lb-control-03 systemd[1]: mantl-storage-setup.service failed.
```

- Ansible version (`ansible --version`): 1.9.4
- Python version (`python --version`): 2.7.11
- Git commit hash or branch: master
- Cloud Environment: all
- Terraform version (`terraform version`): 0.7.0

**Comment by siddharthist** [comment]
Same failure when `debug_storage_setup=True`.

**Comment by siddharthist** [comment]
Just ran into this again.

**Comment by sehqlr** [comment]
Who should triage this one?

**Comment by stevendborrelli** [comment]
@sehqlr you can try....on platforms without an external volume, we should not be trying to create a new VG/LV
