### ISSUE TITLE
HDFS fails to activate namenode2 when namenode1 is down

### ISSUE THREAD

**Issue by aitzkowi** [CiscoCloud/mantl#1726]
mantl 1.1.0 on AWS. cluster with 1 workers.
I deployed HDFs via mantl-api.
I manually shit-off the worker running namenode1 (the active namenode), and expected namenode2 to become the active namenode.
However, namenode2 failed to becaome the active namenode with the following error:

16/07/17 10:17:11 FATAL namenode.NameNode: Failed to start namenode.
java.lang.IllegalArgumentException: Unable to construct journal, qjournal://journalnode1.service.consul:8485;journalnode2.service.consul:8485;journalnode3.service.consul:8485/hdfs
	at org.apache.hadoop.hdfs.server.namenode.FSEditLog.createJournal(FSEditLog.java:1582)
	at org.apache.hadoop.hdfs.server.namenode.FSEditLog.initJournals(FSEditLog.java:275)
	at org.apache.hadoop.hdfs.server.namenode.FSEditLog.initSharedJournalsForRead(FSEditLog.java:253)
	at org.apache.hadoop.hdfs.server.namenode.FSImage.initEditLog(FSImage.java:772)
	at org.apache.hadoop.hdfs.server.namenode.FSImage.loadFSImage(FSImage.java:620)
	at org.apache.hadoop.hdfs.server.namenode.FSImage.recoverTransitionRead(FSImage.java:281)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.loadFSImage(FSNamesystem.java:1005)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.loadFromDisk(FSNamesystem.java:735)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.loadNamesystem(NameNode.java:531)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.initialize(NameNode.java:587)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.<init>(NameNode.java:754)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.<init>(NameNode.java:738)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.createNameNode(NameNode.java:1427)
	at org.apache.hadoop.hdfs.server.namenode.NameNode.main(NameNode.java:1493)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.apache.hadoop.hdfs.server.namenode.FSEditLog.createJournal(FSEditLog.java:1580)
	... 13 more
Caused by: java.lang.NullPointerException
	at org.apache.hadoop.hdfs.qjournal.client.IPCLoggerChannelMetrics.getName(IPCLoggerChannelMetrics.java:107)
	at org.apache.hadoop.hdfs.qjournal.client.IPCLoggerChannelMetrics.create(IPCLoggerChannelMetrics.java:91)
	at org.apache.hadoop.hdfs.qjournal.client.IPCLoggerChannel.<init>(IPCLoggerChannel.java:178)
	at org.apache.hadoop.hdfs.qjournal.client.IPCLoggerChannel$1.createLogger(IPCLoggerChannel.java:156)
	at org.apache.hadoop.hdfs.qjournal.client.QuorumJournalManager.createLoggers(QuorumJournalManager.java:367)
	at org.apache.hadoop.hdfs.qjournal.client.QuorumJournalManager.createLoggers(QuorumJournalManager.java:149)
	at org.apache.hadoop.hdfs.qjournal.client.QuorumJournalManager.<init>(QuorumJournalManager.java:116)
	at org.apache.hadoop.hdfs.qjournal.client.QuorumJournalManager.<init>(QuorumJournalManager.java:105)
	... 18 more
16/07/17 10:17:11 INFO util.ExitUtil: Exiting with status 1
16/07/17 10:17:11 INFO namenode.NameNode: SHUTDOWN_MSG: 
/************************************************************
SHUTDOWN_MSG: Shutting down NameNode at aliza-worker-005/10.1.2.87
************************************************************/

To my understanding, the problem occurred because journalnode1 was also down (it was on the same machine as namenode1, which i shut off), so namende2 failed to get a quorum on the journal nodes. 
related issue: https://issues.apache.org/jira/browse/HDFS-4210

As a result, HDFS was completely non functional as it had no active name node!
can HDFS be configured differently to avoid this?

Ansible version 1.9.4
Python version 2.7.11
Git commit hash or branch: mantl 1.1.0
Cloud Environment: AWS
Terraform Terraform v0.6.16

**Comment by siddharthist** [comment]
Please remember to wrap all logs and source code in triple backticks: \`\`\`. See [Github's documentation on code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/) for more details.

**Comment by sehqlr** [comment]
@aitzkowi I looked at this issue after #1727, and it seems to me like the two are related, since this issue is caused by the namenode not surviving a reboot. What I would like to do is work on that issue first, and see if this one is solved also.

**Comment by aitzkowi** [comment]
Seems like this issue is related to the following HDFS bugs:
https://issues.apache.org/jira/browse/HDFS-10719

Not clear which HDFS version contains this fix.
