### ISSUE TITLE
calico | unlock neutron ports to allow calico traffic --failing

### ISSUE THREAD

**Issue by tomsherrod** [CiscoCloud/mantl#1779]
Before digging into this, is calico required? Docs say it is optional and default turned off, however, it installs.
If required, pointers in debugging the error welcome and happy work through it. I've verified the OpenStack env variables are correct.

Below is information on the error.  
sample.yml -- no changes
ansible -- 1.9.6
python -- 2.75
git hash: fe2d5bb8a81ab473ea93945a16991a45820f5a70
OpenStack (Liberty)
terraform: v0.6.16

failed: [mantl-worker-001] => (item=mantl-edge-01) => {"changed": false, "cmd": 
"/usr/local/bin/neutron_port_update.py \"192.168.0.0/16\" \"fa:16:3e:74:f3:46\""
, "delta": "0:00:00.573519", "end": "2016-07-31 18:06:13.984957", "failed": true
, "failed_when_result": true, "item": "mantl-edge-01", "rc": 1, "start": "2016-0
7-31 18:06:13.411438", "stdout_lines": [], "warnings": []}
stderr: Traceback (most recent call last):
  File "/usr/local/bin/neutron_port_update.py", line 128, in <module>
    ports = list_ports(token, public_url)
  File "/usr/local/bin/neutron_port_update.py", line 83, in list_ports
    r = requests.get(auth_url, headers=headers)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 68, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 450, in req
uest
    prep = self.prepare_request(req)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 381, in pre
pare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 304, in prepa
re
    self.prepare_url(url, params)
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 357, in prepa
re_url
    raise InvalidURL(*e.args)
requests.exceptions.InvalidURL: Failed to parse: openstackhostname:9696v2.0

**Comment by vpanizo** [comment]
I recently experienced a similar error with an Openstack lab. It appears that the configured endpoint is not consistent across Openstack installations.
 
diff --git a/roles/calico/files/neutron_port_update.py b/roles/calico/files/neutron_port_update.py
index e7dd6c9..c21adfc 100755
--- a/roles/calico/files/neutron_port_update.py
+++ b/roles/calico/files/neutron_port_update.py
@@ -125,6 +125,7 @@ if __name__ == "__main__":
     catalog = get_catalog()
     token = get_token(catalog)
     public_url = neutron_public_url(catalog)
+    public_url = public_url + "/"
     ports = list_ports(token, public_url)

     exit_code = 0 # no update to port

**Comment by vpanizo** [comment]
I recently experienced a similar error with an Openstack lab. It appears that the configured endpoint is not consistent across Openstack installations.
```
diff --git a/roles/calico/files/neutron_port_update.py b/roles/calico/files/neutron_port_update.py
index e7dd6c9..c21adfc 100755
--- a/roles/calico/files/neutron_port_update.py
+++ b/roles/calico/files/neutron_port_update.py
@@ -125,6 +125,7 @@ if __name__ == "__main__":
     catalog = get_catalog()
     token = get_token(catalog)
     public_url = neutron_public_url(catalog)
+    public_url = public_url + "/"
     ports = list_ports(token, public_url)

     exit_code = 0 # no update to port
```

**Comment by tomsherrod** [comment]
Simple enough! Install finished. Took some logging on to individual machines to get docker restarted before all reports cleared. Successful.

Thank you.

**Comment by siddharthist** [comment]
@vpanizo Is that a fix that we could make as part of Mantl? Would you be willing to make a PR?

**Comment by vpanizo** [comment]
Certainly. I'll go ahead PR a fix.

**Comment by sehqlr** [comment]
@vpanizo: You can also fork the repo, and issue a PR from that. I'd be happy to manually test for you.
