### ISSUE TITLE
NOTIFIED: [marathon | wait for marathon to listen]

### ISSUE THREAD

**Issue by tymofii-polekhin** [CiscoCloud/mantl#894]
I keep seeing this errors every deployment of Mantl
```
failed: [mi-control-02] => {"changed": true, "cmd": ["/usr/local/bin/marathon-wait-for-listen.sh"], "delta": "0:02:00.814128", "end": "2015-12-07 14:10:41.044301", "rc": 2, "start": "2015-12-07 14:08:40.230173", "warnings": []}
```
This time i have 3 master - 1 failure, when i use 5 masters - i get 2 failures

**Comment by Zogg** [comment]
Which cloud do you use?

**Comment by tymofii-polekhin** [comment]
OpenStack

**Comment by stevendborrelli** [comment]
I came across this on a node. Marathon was running, but not listening. This might be a culprit in the logs: 

```
Dec 13 18:40:56 sb-mantl-control-02 marathon[29840]: Exception in thread "main" com.google.inject.CreationException: Guice creation errors:
Dec 13 18:40:56 sb-mantl-control-02 marathon[29840]: 
Dec 13 18:40:56 sb-mantl-control-02 marathon[29840]: 1) Tried proxying mesosphere.marathon.MarathonScheduler to support a circular dependency, but it is not an interface.
Dec 13 18:40:56 sb-mantl-control-02 marathon[29840]: at mesosphere.marathon.MarathonModule.configure(MarathonModule.scala:74)
Dec 13 18:40:56 sb-mantl-control-02 marathon[29840]: while locating mesosphere.marathon.MarathonScheduler
Dec 13 18:40:56 sb-mantl-control-02 marathon[29840]: for parameter 1 at mesosphere.marathon.health.MarathonHealthCheckManager.<init>(MarathonHealthCheckManager.scala:24)
Dec 13 18:40:56 sb-mantl-control-02 marathon[29840]: while locating mesosphere.marathon.health.MarathonHealthCheckManager
Dec 13 18:40:56 sb-mantl-control-02 marathon[29840]: at mesosphere.marathon.MarathonModule.configure(MarathonModule.scala:84)
Dec 13 18:40:56 sb-mantl-control-02 marathon[29840]: while locating mesosphere.marathon.health.HealthCheckManager
Dec 13 18:40:56 sb-mantl-control-02 marathon[29840]: for parameter 4 at mesosphere.marathon.MarathonScheduler.<init>(MarathonScheduler.scala:29)
```

Apparently marathon has cyclic dependencies internally. https://mesosphere.github.io/marathon/docs/core-architecture.html

Maybe we try a newer version of marathon to see if the behavior is still there. 0.9.0 is a few months old.

**Comment by ryane** [comment]
I've been running into this intermittently on new builds as well - same exception as above.

**Comment by siddharthist** [comment]
Is this still an issue? I haven't seen this recently.

**Comment by siddharthist** [comment]
Closing because I've not seen this for a while. Please reopen if it's still an issue!
